# -*- coding: utf-8 -*-
"""DFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZ67IOrp0e0Aq3TwDCF_jM8-4Jzo48aa
"""

graph = {
    '5' : ['3','7'],
    '3' : ['2','4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
}                            #DFS CODE
visited = set()     #set to keep track of visited nodes of graph
def dfs(visited,graph,node):
  if node not in visited:
    print(node)
    visited.add(node)
    for neighbour in graph[node]:
      dfs(visited, graph, neighbour)
#Driver code
print("Following is the Depth-First Search")
dfs(visited,graph,'5')