# -*- coding: utf-8 -*-
"""RANDOM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZ67IOrp0e0Aq3TwDCF_jM8-4Jzo48aa
"""

import random
GRID_SIZE = 5
def initialize_grid(size):
    return [['D' if random.random() < 0.3 else 'C' for _ in range(size)] for _ in range(size)]
def display_grid(grid):
    for row in grid: print(' '.join(row))
    print()
class RandomAgent:
    def __init__(self, grid):
        self.grid, self.x, self.y = grid, random.randint(0, GRID_SIZE - 1), random.randint(0, GRID_SIZE - 1)
    def move(self):
        moves = [(dx, dy) for dx, dy in [(-1, 0), (1, 0), (0, -1), (0, 1)]
                 if 0 <= self.x + dx < GRID_SIZE and 0 <= self.y + dy < GRID_SIZE]
        self.x, self.y = self.x + random.choice(moves)[0], self.y + random.choice(moves)[1]
    def perform_action(self):
        if self.grid[self.x][self.y] == 'D':
            self.grid[self.x][self.y] = 'C'
            print(f"Cleaned cell ({self.x}, {self.y})")
        else:
            self.move()
            print(f"Moved to cell ({self.x}, {self.y})")
def main():
    grid = initialize_grid(GRID_SIZE)
    agent = RandomAgent(grid)
    print("Initial Grid:")
    display_grid(grid)
    for _ in range(10):
        agent.perform_action()
        display_grid(grid)
if __name__ == "__main__":
    main()